### ISSUE TITLE
ReasonML plugin not compatible with IntelliJ 2020.2.1

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#266] opened 2020-09-04 03:17 UTC
plugin version: 0.91-2020.1

![image](https://user-images.githubusercontent.com/1253341/92195625-49a3ed00-ee22-11ea-88f9-0517c972e2df.png)

**Comment by giraud** [comment] 2020-09-04 09:39
Duplicate of #259 , plugin is not compatible yet

**Closed by giraud** 2020-09-04 09:39 UTC
