### ISSUE TITLE
Tab-complete for bound components defined in tuples does not work

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-editor/reasonml-idea-plugin#206] opened 2019-12-27 06:24 UTC
plugin version: 0.8.4-2019.3

### Description

If I capture bindings for a tuple, like this common pattern using React's `useState` hook:

```
let (selectedRows, setSelectedRows) = React.useState(() => [||]);
```

I'm unable to tab-complete either `selectedRows` or `setSelectedRows`. Instead, the plugin suggests `(selectedRows, setSelectedRows)` as the tab completion value.

**Comment by giraud** [comment] 2020-02-18 08:45
Duplicate of #167

**Closed by giraud** 2020-02-18 08:45 UTC
