### ISSUE TITLE
CPU exhaustion

### ISSUE THREAD

**Issue by keynan** [reasonml-editor/reasonml-idea-plugin#44] opened 2018-04-09 01:47 UTC
plugin version: 0.44

### Description
For some reason the presence of this plugin causes idea to monopolise a single cpu core in perpetuity. Once running it takes ~ 30 seconds for it to reach 100%cpu utilization and whatever job it's performing never completes.

**Comment by giraud** [comment] 2018-04-09 10:01
Hi,
I can't do much with that information.
Can you record a cpu profile ? you can read how to here: https://intellij-support.jetbrains.com/hc/en-us/articles/207241235.
also, are you doing anything special before the cpu goes high ? is your project available on github ?
thanks

**Comment by keynan** [comment] 2018-04-13 12:06
Per the instructions on that link I produced 2 profiles, sending seperately
b/c github has trouble with the file sizes. I replicated the CPU spin-up by
code navigating to Js.Typed_array, then to one of the included modules. The
project is not open sourced yet but I've included the package, webpack, and
bsconfig files below.


{
  "name": "",
  "version": "0.1.0",
  "scripts": {
    "build": "bsb -make-world",
    "start": "bsb -make-world -w",
    "clean": "bsb -clean-world",
    "test": "echo \"Error: no test specified\" && exit 1",
    "webpack": "webpack -w",
    "webpack:production": "NODE_ENV=production webpack"
  },
  "keywords": [
    "BuckleScript"
  ],
  "author": "",
  "dependencies": {
    "bs-fetch": "^0.2.1",
    "bs-json": "^1.0.1",
    "bs-ocaml-protoc-json": "^0.1.1",
    "bs-webapi": "^0.8.3",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "reason-react": ">=0.3.4",
    "text-encoding": "^0.6.4"
  },
  "devDependencies": {
    "bs-platform": "^2.2.3",
    "reason-cli": "^3.1.0-linux",
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.10"
  }
}


/* This is the BuckleScript configuration file. Note that this is a comment;
  BuckleScript comes with a JSON parser that supports comments and trailing
  comma. If this screws with your editor highlighting, please tell us by filing
  an issue! */
{
  "name": "",
  "reason": {
    "react-jsx": 2
  },
  "sources": {
    "dir": "src",
    "subdirs": true
  },
  "package-specs": [
    {
      "module": "commonjs",
      "in-source": true
    }
  ],
  "suffix": ".bs.js",
  "namespace": true,
  "bs-dependencies": [
    "reason-react",
    "bs-webapi",
    "bs-fetch",
    "bs-json",
    "bs-ocaml-protoc-json"
  ],
  "refmt": 3,
  "warnings": {
    "error": "+5"
  }
}

const path = require('path');
const outputDir = path.join(__dirname, "../assets/");

const isProd = process.env.NODE_ENV === 'production';

module.exports = {
  entry: './src/Index.bs.js',
  mode: isProd ? 'production' : 'development',
  output: {
    path: outputDir,
    publicPath: outputDir,
    filename: 'Index.js',
  },
};

**Comment by keynan** [comment] 2018-04-13 12:57
[GO-181.4203.567_kpratt_13.04.2018_21.55.06.zip](https://github.com/reasonml-editor/reasonml-idea-plugin/files/1907243/GO-181.4203.567_kpratt_13.04.2018_21.55.06.zip)
[GO-181.4203.567_kpratt_13.04.2018_21.58.48.zip](https://github.com/reasonml-editor/reasonml-idea-plugin/files/1907244/GO-181.4203.567_kpratt_13.04.2018_21.58.48.zip)

**Comment by jsiebern** [comment] 2018-04-22 14:11
Same here by now, it shows this when it starts:

```
null
java.util.EmptyStackException
	at com.intellij.util.containers.Stack.pop(Stack.java:58)
	at com.reason.lang.ParserState.pop(ParserState.java:122)
	at com.reason.lang.ParserState.popEnd(ParserState.java:128)
	at com.reason.lang.reason.RmlParser.parseGtAutoClose(RmlParser.java:367)
	at com.reason.lang.reason.RmlParser.parseFile(RmlParser.java:105)
	at com.reason.lang.CommonParser.parseLight(CommonParser.java:52)
	at com.reason.lang.CommonParser.parse(CommonParser.java:29)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:193)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:544)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:247)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:359)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:305)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:241)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:101)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:682)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:473)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:285)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:285)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:245)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by giraud** [comment] 2018-04-23 15:03
Hi, I'm back at work.
thanks @keynan for the reports.

I don't see the cpu usage going crazy in your snapshots.
![image](https://user-images.githubusercontent.com/239612/39134932-1bf3387e-4718-11e8-81c2-b82dd08782dd.png)
![image](https://user-images.githubusercontent.com/239612/39134948-25b411f8-4718-11e8-8c58-01c6e9c89c92.png)

The only hotspots that I can find now are related to DocPreviewUtil class.

**Comment by giraud** [comment] 2018-04-23 15:04
@jsiebern I fixed the stack exception in source

**Comment by giraud** [comment] 2018-04-23 15:04
does the cpu problem happen with a particular project/file ?

**Comment by giraud** [comment] 2018-05-17 21:16
@jfehrle thanks for the precisions.

Such a hard problem to diagnose.

I have found that in 0.5 I was doing some blocking IO operations in the main UI thread. I fixed it in 0.51 and it can help to have a smoother experience. But I have no clue on this  issue yet.

**Comment by jfehrle** [comment] 2018-05-18 15:19
It hard to tell what's going on, and it might be a change in IntelliJ or something else rather than the plugin.  I tried turning the plugin off and watching the CPU usage, I also tried opening a Java project (i.e. no .ml files).  I'm not sure the plugin is the cause of the issue.

If you can reproduce the behavior, you could compare that to a version from a month or two ago and see if that has the same behavior.  If so, look at code changes since then and insert printfs in any place that looks like it loop a lot.  Good luck.

**Comment by giraud** [comment] 2018-06-13 14:52
can you tell me if this behavior is still present in 0.55+ ?

**Comment by jfehrle** [comment] 2018-06-15 02:16
Hervé,
So far it seems better, thanks.  I'll observe it more over the coming days (haven't been doing as much intensive code editing recently).
Jim

**Comment by giraud** [comment] 2018-06-15 07:33
I'll close it after next release if no news until then.

**Comment by giraud** [comment] 2018-06-20 15:16
I'm closing this bug after the 2 bugs I fixed that were making idea freeze. I hope the situation is now much better with 0.55+.

**Closed by giraud** 2018-06-20 15:16 UTC
Labels: :zzz: performance
