### ISSUE TITLE
Settings are shared between opened projects

### ISSUE THREAD

**Issue by Coobaha** [reasonml-editor/reasonml-idea-plugin#69] opened 2018-06-23 16:41 UTC
plugin version: 
0.56
### Description

If I have two projects opened in IDE they share settings

For instance:
1st window is Reason project where I have 80 default `refmt` width and no auto reformat on save
2nd window is any project other project with default plugin settings (120 width and auto reformat)

I hit save in 1st window and plugin reformats it with settings from second project :D 

I am not sure but it could be so that 2nd project should have deep folder with Reason project.

P.S. Please make default print width to respect `refmt` default width (80) or at least it would be nice to define global setting ;) 🙏

**Comment by giraud** [comment] 2018-06-25 07:21
Hi, settings are per projects, you can [see in the screenshots](https://github.com/reasonml-editor/reasonml-idea-plugin/wiki/Configure-a-bucklescript-project) a text saying "For current project".
Settings are stored in a reason.xml file in you .idea directory, you should look for this file to check everything is correctly saved.
I checked again and refmt is using settings from project configuration.

**Comment by Coobaha** [comment] 2018-06-25 09:58
@giraud 
I can reproduce this with three IDE projects
1) reason project A with .idea - my plugin settings
2) reason project B with .idea - my plugin settings
3) project C with .idea which deep folder with project B  - default plugin settings

Then
1) Open project A
2) Open project C
3) Edit project A and save
4) ????

It shares settings only when save action is called.

**Comment by giraud** [comment] 2018-06-26 09:47
okay. I don't know if it's an intended behavior or a bug in jetbrains product then.

**Comment by giraud** [comment] 2018-10-14 15:18
I'm closing this issue because I reworked how compiler and refmt are instanciated in 0.65.
But I'm still not sure it is really fixed.

**Closed by giraud** 2018-10-14 15:18 UTC
Labels: :raising_hand_woman: enhancement
