### ISSUE TITLE
com.reason.CompilerProcessException: Dune process exception. Invalid cliType command.

### ISSUE THREAD

**Issue by hartmut27** [reasonml-editor/reasonml-idea-plugin#234] opened 2020-04-25 22:35 UTC
plugin version:  0.88.0-2020.1

On Linux/Ubuntu after save file, I receive an Exception `Dune process exception. Invalid cliType command`.

In the shell,`esy dune build` works perfect.

( btw. how could I tell the plugin to take `esy dune ...` instead of `dune...` )

Log:

> 2020-04-26 00:27:08,354 [  35204]   INFO - rationStore.ComponentStoreImpl - Saving Project (name=zabl_re, containerState=ACTIVE, componentStore=/home/hape/zabl_re) XDebuggerManager took 12 ms 
> 2020-04-26 00:28:13,489 [ 100339]  ERROR - llij.ide.plugins.PluginManager - Dune process exception. Invalid cliType command. 
> com.reason.CompilerProcessException: Dune process exception. Invalid cliType command.
>         at com.reason.esy.EsyProcess.recreate(EsyProcess.java:158)
>         at com.reason.dune.DuneCompiler.run(DuneCompiler.java:62)
>         at com.reason.ide.console.CompilerAction.doAction(CompilerAction.java:50)
>         at com.reason.ide.console.BsMakeWorldAction.actionPerformed(BsMakeWorldAction.java:20)
>         at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:280)
>         at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:274)
>         at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
>         at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
>         at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:438)
>         at java.desktop/java.awt.Component.processEvent(Component.java:6416)
>         at java.desktop/java.awt.Container.processEvent(Container.java:2263)
>         at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5026)
>         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
>         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
>         at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
>         at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
>         at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
>         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
>         at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
>         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4858)
>         at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
>         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
>         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
>         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
>         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
>         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
>         at java.base/java.security.AccessController.doPrivileged(Native Method)
>         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
>         at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
>         at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
>         at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:912)
>         at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
>         at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
>         at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:739)
>         at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
>         at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
>         at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
>         at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
>         at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
>         at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
>         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
>         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>         at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> 2020-04-26 00:28:13,491 [ 100341]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1  Build #IU-201.6668.121 
> 2020-04-26 00:28:13,491 [ 100341]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
> 2020-04-26 00:28:13,492 [ 100342]  ERROR - llij.ide.plugins.PluginManager - OS: Linux 
> 2020-04-26 00:28:13,492 [ 100342]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: ReasonML version: 0.88.0-2020.1 
>

**Comment by giraud** [comment] 2020-04-27 06:56
Hi, esy is not yet supported, work is in progress.

**Comment by JohnPucciarelli** [comment] 2020-04-27 15:25
I have a branch that adds proper esy support. I'll update this issue once the PR is ready.

**Comment by Coobaha** [comment] 2020-04-30 07:54
I think this also affects Bucklescript commands. My hotkeys are not working anymore, and can't execute clean & build command from toolbar or actions

**Comment by Coobaha** [comment] 2020-04-30 09:13
@JohnPucciarelli @giraud This is 0.88 regression, 0.87 is working fine

**Comment by Coobaha** [comment] 2020-05-01 16:23
Aha, found the reason. Bsb action was named "Build" before and now it was changed to Make. I had keybinding for Build action and it was migrated to Esy's build 😿 I've noticed that action names for esy/dune/bsb can clash and it is not clear what action you are supposed to bind. Fixed here https://github.com/reasonml-editor/reasonml-idea-plugin/pull/238

**Comment by giraud** [comment] 2020-05-02 07:48
should be fixed in 0.88.1 (2019.3/2020.1)

**Closed by giraud** 2020-05-02 07:48 UTC
