### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by acierto** [reasonml-editor/reasonml-idea-plugin#5] opened 2017-07-14 07:04 UTC
Just opened my project in idea and see the next error

![screen shot 2017-07-14 at 09 02 56](https://user-images.githubusercontent.com/2265094/28201886-50bef7c0-6873-11e7-9210-2f97effc9229.png)

You can use for the reference this repo to reproduce it: [ts-explorer](https://github.com/acierto/ts-explorer)

**Comment by giraud** [comment] 2017-08-11 08:28
Thanks, updated in next release

**Comment by giraud** [comment] 2017-08-16 20:24
Closing that issue because I don't reproduce it with 0.12.
Feel free to reopen it if it's not the case

**Closed by giraud** 2017-08-16 20:24 UTC
