### ISSUE TITLE
Missing/extraneous items in Structure panel for classes

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#269] opened 2020-09-17 19:02 UTC
plugin version: 0.92-2020.2

The panel should show the methods defined on the right.  (Adding implementations doesn't change the display.  And the items that are in the panel should not be there.

IMHO It's going to be difficult to get this code to work reliably without a way to create and run regression tests.  (Perhaps with a better parser...)

![image](https://user-images.githubusercontent.com/1253341/93515117-f24f5380-f8dc-11ea-9766-c79ac00b8cea.png)

class type ops =
object
  method go_to_insert : unit task
  method go_to_mark : GText.mark -> unit task
  method process_next_phrase : unit task

  method get_n_errors : int
  method get_errors : (int * string) list
  method get_slaves_status : int * int * string CString.Map.t

  method handle_failure : handle_exn_rty -> unit task

  method destroy : unit -> unit
end

**Comment by jfehrle** [comment] 2020-09-17 20:42
This makes the structure panel unusable for classes; much worse than in the previous release.  :-(

**Comment by giraud** [comment] 2020-09-18 08:52
Sorry for the inconvenience, it's fixed in 0.92.1.
This is not a parser problem, but comes from the latest work on references. 
I'm not able to spot these problems because I'm not doing any OCaml and not using classes at all.

By the way, I already have many unit tests for the parser for non regression, you can find them in tests/com/reason/lang/ocaml.

**Closed by giraud** 2020-09-18 08:52 UTC
Labels: :bug: bug
