### ISSUE TITLE
IJ stack trace

### ISSUE THREAD

**Issue by jfehrle** [reasonml-editor/reasonml-idea-plugin#80] opened 2018-07-17 02:29 UTC
plugin version: 0.58

### Description
Not sure what I'm getting this exception, but I got it 3 times.

Let me know if this is not a useful report--if so I'll refrain in the future.

```
com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to com.intellij.psi.impl.source.tree.CompositeElement
java.lang.ClassCastException: com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to com.intellij.psi.impl.source.tree.CompositeElement
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:160)
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:153)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:75)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:27)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:972)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:954)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:197)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.diff(DiffTree.java:61)
	at com.intellij.psi.impl.BlockSupportImpl.diffTrees(BlockSupportImpl.java:336)
	at com.intellij.lang.impl.PsiBuilderImpl.merge(PsiBuilderImpl.java:996)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:910)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:901)
	at com.reason.lang.CommonParser.parse(CommonParser.java:31)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:193)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:544)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:247)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:359)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:305)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:241)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:101)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:682)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:473)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:285)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:285)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:245)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.ClassCastException: com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to com.intellij.psi.impl.source.tree.CompositeElement
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:160)
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:153)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:75)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:27)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:972)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:954)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:197)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.diff(DiffTree.java:61)
	at com.intellij.psi.impl.BlockSupportImpl.diffTrees(BlockSupportImpl.java:336)
	at com.intellij.lang.impl.PsiBuilderImpl.merge(PsiBuilderImpl.java:996)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:910)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:901)
	at com.reason.lang.CommonParser.parse(CommonParser.java:31)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:193)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:544)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:247)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:359)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:305)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:241)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:101)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:682)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:473)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:285)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:285)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:245)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.ClassCastException: com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to com.intellij.psi.impl.source.tree.CompositeElement
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:160)
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:153)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:75)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:27)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:972)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:954)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:197)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.diff(DiffTree.java:61)
	at com.intellij.psi.impl.BlockSupportImpl.diffTrees(BlockSupportImpl.java:336)
	at com.intellij.lang.impl.PsiBuilderImpl.merge(PsiBuilderImpl.java:996)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:910)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:901)
	at com.reason.lang.CommonParser.parse(CommonParser.java:31)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:193)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:544)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:247)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:359)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:305)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:241)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:101)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:682)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:473)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:285)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:285)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:245)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.ClassCastException: com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to com.intellij.psi.impl.source.tree.CompositeElement
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:160)
	at com.intellij.psi.impl.DiffLog$InsertEntry.<init>(DiffLog.java:153)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:75)
	at com.intellij.psi.impl.DiffLog.nodeInserted(DiffLog.java:27)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:972)
	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:954)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:197)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.build(DiffTree.java:151)
	at com.intellij.util.diff.DiffTree.diff(DiffTree.java:61)
	at com.intellij.psi.impl.BlockSupportImpl.diffTrees(BlockSupportImpl.java:336)
	at com.intellij.lang.impl.PsiBuilderImpl.merge(PsiBuilderImpl.java:996)
	at com.intellij.lang.impl.PsiBuilderImpl.buildTree(PsiBuilderImpl.java:910)
	at com.intellij.lang.impl.PsiBuilderImpl.getTreeBuilt(PsiBuilderImpl.java:901)
	at com.reason.lang.CommonParser.parse(CommonParser.java:31)
	at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:88)
	at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:49)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.lambda$ensureParsed$0(LazyParseableElement.java:193)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:544)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.ensureParsed(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:247)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:40)
	at com.intellij.psi.impl.BlockSupportImpl.isReplaceWholeNode(BlockSupportImpl.java:359)
	at com.intellij.psi.impl.BlockSupportImpl.mergeTrees(BlockSupportImpl.java:305)
	at com.intellij.psi.impl.BlockSupportImpl.makeFullParse(BlockSupportImpl.java:241)
	at com.intellij.psi.impl.BlockSupportImpl.reparse(BlockSupportImpl.java:101)
	at com.intellij.psi.impl.DocumentCommitThread.doCommit(DocumentCommitThread.java:682)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$commitUnderProgress$4(DocumentCommitThread.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134)
	at com.intellij.psi.impl.DocumentCommitThread.commitUnderProgress(DocumentCommitThread.java:473)
	at com.intellij.psi.impl.DocumentCommitThread.lambda$pollQueue$1(DocumentCommitThread.java:285)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.psi.impl.DocumentCommitThread.pollQueue(DocumentCommitThread.java:285)
	at com.intellij.psi.impl.DocumentCommitThread.run(DocumentCommitThread.java:245)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:212)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by giraud** [comment] 2018-07-17 06:09
I'm working on it, this is a duplicate of #79 . I don't understand why yet. It happens only in insert mode.

**Closed by giraud** 2018-07-17 06:09 UTC
